# cannot use yarn pnp because of no good solutions of
# problem 'ESLint couldn't find the plugin "eslint-plugin-import"'
# when import my package with eslint deps INSIDE (@wttsolutions/eslint-config)
nodeLinker: "node-modules"

enableGlobalCache: false

